### ISSUE TITLE
pve下centos7防火墙问题

### ISSUE THREAD

**Issue by ntgeralt** [233boy/ss#1]
你好，感谢你制作的一键脚本。在GCP的centos7测试你脚本是正常的。
但pve的centos7重启之后防火墙SS:7777规则丢失。
ssh需执行firewall-cmd --zone=public --add-port=7777/tcp --permanent才解决问题,这里反馈一下

**Comment by 233boy** [comment]
@ntgeralt 
因为我没处理这个防火墙规则 😂 
理论上，普遍大厂，或者国际大厂，及其他的一些常见的商家 是不会有问题的。
